# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.CharField(db_index=True, help_text='Secret key this host uses to identify itself.', max_length=32, unique=True)),
                ('identifier', models.CharField(db_index=True, help_text='Unique identifier for this system (usually hostname).', max_length=255)),
                ('last_seen', models.DateTimeField(auto_now_add=True, help_text='Last time this host checked in.')),
                ('invalidate', models.BooleanField(default=False, help_text='Whether this node should be re-enrolled from scratch next time it checks in.')),
                ('architecture', models.CharField(blank=True, db_index=True, help_text='Machine architecture.', max_length=200)),
                ('release', models.CharField(blank=True, db_index=True, help_text='Operating system release.', max_length=200)),
                ('cpu', models.CharField(blank=True, help_text='Model of CPU installed.', max_length=200)),
                ('ram', models.BigIntegerField(blank=True, help_text='Amount of RAM installed (KiB).')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('output', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Host')),
            ],
            options={
                'verbose_name_plural': 'log entries',
            },
        ),
        migrations.CreateModel(
            name='LogQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name for the query', max_length=255)),
                ('query', models.CharField(help_text='The query to be executed', max_length=255)),
                ('interval', models.IntegerField(default=10, help_text='How often should the query be run (in seconds)?')),
            ],
            options={
                'verbose_name_plural': 'log queries',
            },
        ),
    ]
