# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(allow_unicode=True, help_text='Descriptive slug name for the tag', max_length=22)),
            ],
        ),
        migrations.AddField(
            model_name='logquery',
            name='snapshot',
            field=models.BooleanField(default=False, help_text='Whether this query should send a report even when the data may not have changed. Useful for time series metrics and keepalives.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logquery',
            name='name',
            field=models.CharField(help_text='Descriptive name for the query', max_length=255),
        ),
        migrations.AddField(
            model_name='host',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
        migrations.AddField(
            model_name='logquery',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
    ]
